name:                cofs
version:             0.1.0.0
github:              "githubuser/cofs"
license:             BSD3
author:              "Axel Ramge"
maintainer:          "axel@ramge.de"
copyright:           "2020 Axel Ramge"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cofs#readme>

dependencies:
- base >= 4.7 && < 5
- colour >= 2.3.5
- diagrams >= 1.4
- diagrams-svg
  # - diagrams-canvas
- diagrams-lib
  # - diagrams-cairo

library:
  source-dirs: src

executables:
  cofs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cofs

tests:
  cofs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cofs
